http:
  port: 3000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  userApi:
    host: "*"
    path: "/user/*"
  dataApi:
    host: "*"
    path: "/data*"
serviceEndpoints:
  userService:
    url: ${SERVICE_ENDPOINT_USER}
  dataService:
    url: ${SERVICE_ENDPOINT_DATA}
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  userPipeline:
    apiEndpoints:
      - userApi
    policies:
      - log:
          - action:
              message: "User request: ${req.method} ${req.url}"
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
              headers:
                x-api-key: ${API_KEY}
  dataPipeline:
    apiEndpoints:
      - dataApi
    policies:
      - log:
          - action:
              message: "Data request: ${req.method} ${req.url}"
      - proxy:
          - action:
              serviceEndpoint: dataService
              changeOrigin: true
              headers:
                x-api-key: ${API_KEY}
